configured_endpoints: 9
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/miru-ml%2Fmiru-device-9dd40f9f87ba771c9aab87536bbe524ebb290e5363e0b2d3ffaced63df8a9bd3.yml
openapi_spec_hash: a3a69db05cf29fd28c78be18fff1e1dd
config_hash: a4ae4428a072e75f1309f5fd10b98086
